In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r'D:\Parkinson_project\data\featured_data.csv')
df = df.drop('Unnamed: 0',axis=1)
df.head()

numPulses  GNE_NSR_SEO  mean_MFCC_1st_coef  mean_MFCC_6th_coef  \
0      240.0       3.0152              8.4781            -1.51440   
1      234.0       3.0600              8.5008            -1.67590   
2      232.0       3.0309              7.6362            -1.49290   
3      178.0       3.0293              6.7365            -0.65556   
4      236.0       3.0362              6.4634            -0.51876   

   std_MFCC_8th_coef  tqwt_energy_dec_27  tqwt_energy_dec_31  \
0            0.17101            0.108070            0.000007   
1            0.16785            0.098360            0.000015   
2            0.21901            0.106910            0.000026   
3            0.24529            0.002072            0.000207   
4            0.22090            0.001152            0.000166   

   tqwt_energy_dec_35  tqwt_entropy_shannon_dec_32  tqwt_TKEO_mean_dec_21  \
0            0.000001                     0.036109               0.010913   
1            0.000002                     0.068996               0.007092   
2            0.000004                     0.050766               0.002236   
3            0.000054                     4.267800               0.105100   
4            0.000028                     3.941400               0.118100   

   ...  tqwt_medianValue_dec_26  tqwt_medianValue_dec_34  \
0  ...            -2.220000e-17                -0.000202   
1  ...            -3.790000e-17                -0.000158   
2  ...            -1.580000e-17                -0.000136   
3  ...             1.105400e-03                -0.000313   
4  ...             8.909500e-03                 0.000663   

   tqwt_meanValue_dec_9  tqwt_meanValue_dec_11  tqwt_meanValue_dec_21  \
0          1.230000e-20          -1.630000e-20          -6.330000e-20   
1          2.030000e-20          -1.680000e-20           3.090000e-19   
2         -1.050000e-21           7.080000e-22           1.760000e-19   
3          2.940000e-20           5.630000e-20           7.780000e-19   
4         -1.170000e-20           1.280000e-20          -1.700000e-18   

   tqwt_meanValue_dec_26  tqwt_skewnessValue_dec_3  tqwt_skewnessValue_dec_21  \
0          -7.210000e-19              1.110000e-15              -4.470000e-17   
1           3.150000e-19             -3.290000e-15              -7.020000e-20   
2          -2.700000e-19             -3.420000e-15               1.200000e-16   
3          -2.340000e-18              6.455000e-02              -1.281100e-03   
4          -8.110000e-19             -4.187600e-03               3.441400e-03   

   tqwt_skewnessValue_dec_28  class  
0                  -0.102900    1.0  
1                  -0.005679    1.0  
2                  -0.003824    1.0  
3                   0.027619    1.0  
4                   0.011756    1.0  

[5 rows x 21 columns]

In [3]:
df['class'] = df['class'].astype('int64')

In [4]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

x = df.drop('class',axis = 1)
y = df['class']

X_train , X_test , y_train , y_test = train_test_split(x,y,train_size=0.7,random_state=28,stratify=y)


# Gradient Boosting Algorithm 

Gradient boosting (GB) generates new modelssequentially from an ensemble of poor models with the aimof minimizing the loss function with each new model [31].The gradient descent method is used to calculate the lossfunction and hence, every new model is more accuratelyfitted with the use of the loss function. Thus, the overallaccuracy is increased as a result of the observations. On theother hand, boosting must be stopped at some point;otherwise, the model would be overfitted. 



In [5]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import f1_score,confusion_matrix,recall_score,precision_score,accuracy_score

### Before Tuning

In [6]:
GB_model = GradientBoostingClassifier()
GB_model.fit(X_train, y_train)
pred2 = GB_model.predict(X_test)

In [7]:
print(f1_score(y_test,pred2))
print(recall_score(y_test,pred2))
print(precision_score(y_test,pred2))
print(confusion_matrix(y_test,pred2))

accuracy_score(y_test,pred2)

0.9277777777777777
0.9881656804733728
0.8743455497382199
[[ 34  24]
 [  2 167]]


0.8854625550660793

#### After tuning

In [8]:
param_grid = {'learning_rate':[0.1,0.5,1,5],'n_estimators':[100,200,300],'max_depth':[3,4,6,10]}

gridGB = GridSearchCV(GradientBoostingClassifier(),param_grid,cv=3,verbose=1,scoring='accuracy')
gridGB.fit(X_train, y_train)

Fitting 3 folds for each of 48 candidates, totalling 144 fits


GridSearchCV(cv=3, estimator=GradientBoostingClassifier(),
             param_grid={'learning_rate': [0.1, 0.5, 1, 5],
                         'max_depth': [3, 4, 6, 10],
                         'n_estimators': [100, 200, 300]},
             scoring='accuracy', verbose=1)

In [9]:
gridGB.best_score_

0.8562853107344632

In [10]:
gridGB.best_params_

{'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 300}

In [11]:
pred3 = gridGB.predict(X_test)

print(f1_score(y_test,pred3))
print(recall_score(y_test,pred3))
print(precision_score(y_test,pred3))
print(confusion_matrix(y_test,pred3))

accuracy_score(y_test,pred3)

0.9217877094972067
0.9763313609467456
0.873015873015873
[[ 34  24]
 [  4 165]]


0.8766519823788547

after tuning we got increase in acc from 0.82 o 0.86 , and there is reduction of the ft

# Adaboost algorithm 

Adaptive Boosting is a machine learning algorithmwhich can be flexible to transform a collection of weak dataitem to strong ones [34]. Hence a strong classifier isconstructed where the learners are trained consecutively.Compared to other classification methods, AdaBoostrequires less twitching of the parameters and is slightersusceptible to data overfitting

In [12]:
from sklearn.ensemble import AdaBoostClassifier

AB = AdaBoostClassifier()
AB.fit(X_train, y_train)
pred4 = AB.predict(X_test)

In [13]:

print(f1_score(y_test,pred4))
print(recall_score(y_test,pred4))
print(precision_score(y_test,pred4))
print(confusion_matrix(y_test,pred4))

accuracy_score(y_test,pred4)

0.9157303370786516
0.9644970414201184
0.8716577540106952
[[ 34  24]
 [  6 163]]


0.8678414096916299

#### After Tuning 

In [14]:
param_grid = {'n_estimators':[50,75,100],'learning_rate':[0.1,0.5,1,5]}
gridab = GridSearchCV(AdaBoostClassifier(),param_grid,cv=3,verbose=1,scoring='accuracy')
gridab.fit(X_train,y_train)

Fitting 3 folds for each of 12 candidates, totalling 36 fits


GridSearchCV(cv=3, estimator=AdaBoostClassifier(),
             param_grid={'learning_rate': [0.1, 0.5, 1, 5],
                         'n_estimators': [50, 75, 100]},
             scoring='accuracy', verbose=1)

In [15]:
gridab.best_params_

{'learning_rate': 1, 'n_estimators': 100}

In [16]:
gridab.best_score_

0.8336329395651428

In [17]:
pred5 = gridab.predict(X_test)

print(f1_score(y_test,pred5))
print(recall_score(y_test,pred5))
print(precision_score(y_test,pred5))
print(confusion_matrix(y_test,pred5))

accuracy_score(y_test,pred5)

0.9121813031161473
0.9526627218934911
0.875
[[ 35  23]
 [  8 161]]


0.8634361233480177

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   numPulses                    756 non-null    float64
 1   GNE_NSR_SEO                  756 non-null    float64
 2   mean_MFCC_1st_coef           756 non-null    float64
 3   mean_MFCC_6th_coef           756 non-null    float64
 4   std_MFCC_8th_coef            756 non-null    float64
 5   tqwt_energy_dec_27           756 non-null    float64
 6   tqwt_energy_dec_31           756 non-null    float64
 7   tqwt_energy_dec_35           756 non-null    float64
 8   tqwt_entropy_shannon_dec_32  756 non-null    float64
 9   tqwt_TKEO_mean_dec_21        756 non-null    float64
 10  tqwt_medianValue_dec_25      756 non-null    float64
 11  tqwt_medianValue_dec_26      756 non-null    float64
 12  tqwt_medianValue_dec_34      756 non-null    float64
 13  tqwt_meanValue_dec_9

# XGB

XG Boost is a gradient boosting framework-basedensemble machine learning algorithm [33]. This algorithmappears to be one of the most effective algorithms forperforming regression, classification, ranking and predictiveanalysis. It is capable of completing a wide range of tasks byusing gradient descent layout to improve weak features indatasets. However, scalability is one of XGBoost's mostimportant features, as it allows for well-structured memoryuse and directs instantaneous training through parallel anddistributed computing. 

In [19]:
import warnings
warnings.filterwarnings('ignore')

In [20]:
from xgboost import XGBClassifier

xgb = XGBClassifier(objective='binary:logistic',
                          booster='gbtree',
                          eval_metric='auc',
                          tree_method='hist',
                          grow_policy='lossguide',
                          use_label_encoder=False)
xgb.fit(X_train, y_train)
pred6 = xgb.predict(X_test)

In [21]:
print(f1_score(y_test,pred6))
print(recall_score(y_test,pred6))
print(precision_score(y_test,pred6))
print(confusion_matrix(y_test,pred6))

accuracy_score(y_test,pred6)

0.9162011173184357
0.9704142011834319
0.8677248677248677
[[ 33  25]
 [  5 164]]


0.8678414096916299

#### Tuning parameters with gridserachcv

In [23]:
param_grid = {'gamma': [0,0.1,1.6,3.2,6.4],
              'learning_rate': [0.01, 0.1, 0.2, 0.300000012, 0.4, 0.5,],
              'max_depth': [5,6,10,14],
              'n_estimators': [50,100,120],
              'reg_alpha': [0,0.1,0.8,1.6,3.2,6.4],
              'reg_lambda': [0,0.1,0.8,1.6,3.2,6.4]}

model = XGBClassifier(objective='binary:logistic',
                          booster='gbtree',
                          eval_metric='auc',tree_method='hist',grow_policy='lossguide',use_label_encoder=False)
gridxgb = GridSearchCV(model,param_grid,cv=3,verbose=1,scoring='accuracy')
gridxgb.fit(X_train, y_train)

Fitting 3 folds for each of 12960 candidates, totalling 38880 fits


GridSearchCV(cv=3,
             estimator=XGBClassifier(base_score=None, booster='gbtree',
                                     colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     enable_categorical=False,
                                     eval_metric='auc', gamma=None, gpu_id=None,
                                     grow_policy='lossguide',
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_delta_step=None,
                                     max_depth=None, min_child_weig...
                                     reg_lambda=None, scale_pos_weight=None,
                                     subsample=None, tree_method='hist',
                                     use_label_encoder=False,
                                   

In [24]:
gridxgb.best_params_

{'gamma': 0,
 'learning_rate': 0.5,
 'max_depth': 5,
 'n_estimators': 100,
 'reg_alpha': 0.8,
 'reg_lambda': 6.4}

In [25]:
gridxgb.best_score_

0.869542886492039

In [30]:
pred7 = gridxgb.predict(X_test)

print(f1_score(y_test,pred7))
print(recall_score(y_test,pred7))
print(precision_score(y_test,pred7))
print(confusion_matrix(y_test,pred7))

accuracy_score(y_test,pred7)

0.923943661971831
0.9704142011834319
0.8817204301075269
[[ 36  22]
 [  5 164]]


0.8810572687224669

# Light GBM (LGBM):

light GBM is another algorithm that performsclassification, ranking and other machine learning tasksusing a gradient boosting system and a decision treealgorithm. It employs a binary tree's leaf wish split methodinstead of level wish splitting, which speeds up data trainingand decreases memory [32]. Moreover, other boostingalgorithms are less compatible with large datasets than LightGBM. Hence, it emerges as one of the best classifiers thatoutperform other algorithms in data training speed andhandling large datasets. 

In [27]:
from lightgbm import LGBMClassifier


In [35]:
LGBM = LGBMClassifier(objective='binary',metric='logloss',is_unbalance=True)
LGBM.fit(X_train, y_train)
pred8 = LGBM.predict(X_test)


In [36]:

print(f1_score(y_test,pred8))
print(recall_score(y_test,pred8))
print(precision_score(y_test,pred8))
print(confusion_matrix(y_test,pred8))

accuracy_score(y_test,pred8)

0.9261363636363636
0.9644970414201184
0.8907103825136612
[[ 38  20]
 [  6 163]]


0.8854625550660793

#### tuning with gridsearchcv

In [37]:
param_grid = {'learning_rate':[0.01,0.1,0.4,0.5,0.75],'max_depth':[5,10,15],'num_leaves':[12,31,39],'reg_alpha':[0.01,0.1,0.5],'reg_lambda':[0.01,0.1,0.5],'subsample':[0.2,0.5]}

model = LGBMClassifier(objective='binary',metric='logloss',is_unbalance=True)

grid_lgbm = GridSearchCV(model,param_grid,cv=3,scoring='accuracy',verbose=1)

grid_lgbm.fit(X_train,y_train)

Fitting 3 folds for each of 810 candidates, totalling 2430 fits


GridSearchCV(cv=3,
             estimator=LGBMClassifier(is_unbalance=True, metric='logloss',
                                      objective='binary'),
             param_grid={'learning_rate': [0.01, 0.1, 0.4, 0.5, 0.75],
                         'max_depth': [5, 10, 15], 'num_leaves': [12, 31, 39],
                         'reg_alpha': [0.01, 0.1, 0.5],
                         'reg_lambda': [0.01, 0.1, 0.5],
                         'subsample': [0.2, 0.5]},
             scoring='accuracy', verbose=1)

In [39]:
grid_lgbm.best_params_

{'learning_rate': 0.75,
 'max_depth': 15,
 'num_leaves': 12,
 'reg_alpha': 0.01,
 'reg_lambda': 0.01,
 'subsample': 0.2}

In [41]:
pred8 = grid_lgbm.predict(X_test)
print(f1_score(y_test,pred8))
print(recall_score(y_test,pred8))
print(precision_score(y_test,pred8))
print(confusion_matrix(y_test,pred8))

accuracy_score(y_test,pred8)

0.9291784702549575
0.9704142011834319
0.8913043478260869
[[ 38  20]
 [  5 164]]


0.8898678414096917